name: Release

on:
  push:
    tags: ['v*.*.*']

jobs:
  release:
    uses: 0xjuanma/simple-release/.github/workflows/reusable-release.yml@main
    with:
      changelog-path: 'CHANGELOG.md'
    secrets:
      RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}

